=== NCIP/cagrid-portal/cagrid-1-0/Demos/06annual/workflow/RPDataService/queries/CqlXpathMap.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2005 U (http://www.xmlspy.com) by Patrick Alan McConnell (Duke University) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="CqlNodeSet">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="CqlNode" maxOccurs="unbounded">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="CqlNodeType"/>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="CqlNodeType">
		<xs:complexContent>
			<xs:extension base="CqlMapType">
				<xs:sequence>
					<xs:element name="CqlProperty" type="CqlPropertiesType" minOccurs="0" maxOccurs="unbounded"/>
					<xs:element name="CqlNode" type="CqlNodeType" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="CqlMapType">
		<xs:attribute name="cqlName" type="xs:string" use="required"/>
		<xs:attribute name="xmlName" type="xs:string" use="required"/>
		<xs:attribute name="xmlPath" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:complexType name="CqlPropertiesType">
		<xs:complexContent>
			<xs:extension base="CqlMapType"/>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>

=== NCIP/cagrid-portal/cagrid-1-0/Demos/06annual/workflow/RPDataService/queries/scanFeatures_map.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2005 U (http://www.xmlspy.com)-->
<CqlNodeSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CqlXpathMap.xsd">
	<CqlNode xmlName="scanFeatures" cqlName="edu.duke.cabig.scanFeatures.ScanFeatures">
		<CqlProperty xmlName="lsid" cqlName="lsid"/>
		<CqlNode xmlName="attributes" cqlName="edu.duke.cabig.scanFeatures.Attributes">
			<CqlProperty xmlName="project" cqlName="project"/>
			<CqlProperty xmlName="patientID" cqlName="patientID"/>
			<CqlProperty xmlName="fractionNumber" cqlName="fractionNumber"/>
			<CqlProperty xmlName="biologicalReplicate" cqlName="biologicalReplicate"/>
			<CqlProperty xmlName="technicalReplicate" cqlName="technicalReplicate"/>
			<CqlProperty xmlName="date" cqlName="date"/>
			<CqlProperty xmlName="outcome" cqlName="outcome"/>
			<CqlProperty xmlName="scanNumber" cqlName="scanNumber"/>
			<CqlProperty xmlName="processingStep" cqlName="processingStep"/>
			<CqlProperty xmlName="lcRetentionTime" cqlName="lcRetentionTime"/>
			<CqlProperty xmlName="experimentalDataLSID" cqlName="experimentalDataLSID"/>
			<CqlProperty xmlName="scanStartPos" cqlName="scanStartPos"/>
			<CqlProperty xmlName="scanStepSize" cqlName="scanStepSize"/>
		</CqlNode>
		<CqlNode xmlName="feature" cqlName="edu.duke.cabig.scanFeatures.Feature">
			<CqlProperty xmlName="@name" cqlName="name"/>
			<CqlNode xmlName="base64" cqlName="edu.duke.cabig.scanFeatures.Base64">
				<CqlProperty xmlName="@type" cqlName="type"/>
				<CqlProperty xmlName="@count" cqlName="type"/>
				<CqlProperty xmlName="." cqlName="value"/>
			</CqlNode>
		</CqlNode>
	</CqlNode>
</CqlNodeSet>
